# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pre: 
     runs-on: ubuntu-latest
      steps:
        - name: Run a multi-line script
          run: |
            echo Hello Action!
        - name: git status
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          run: |
            git config --global credential.helper 'cache --timeout=3600'
            echo "===========   ENV ============"
            env
            echo "===========   LS ============"
            ls -lth
            echo "$(date): $(whoami)Test: ${GITHUB_REPOSITORY}" >> .github/test.log
            echo "===========   git config ============"
            git config -l
            echo "===========   git status ============"
            git checkout -b test
            git status
            echo "===========   git config email ============"
            git config --global user.email "marctimperley@yahoo.co.uk"
            echo "===========   git config name ============"
            git config --global user.name "MarcTimperley"
            echo "===========   git add  ============"
            git add .github/test.log
            echo -e " git remote :\n $(git remote -v)"
            echo -e " git branch :\n $(git branch -v)"
            echo "===========   git commit ============"
            git commit -m "just test"
            echo "===========   git push ============"
    
      #      git subtree push --prefix=.github https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: git remote set-url --push origin https://MarcTimperley:$GITHUB_TOKEN@github.com/response-dashboard
      - run: npm version patch
      - run: npm test
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
